fixed issue #559
middlewarehq/middleware pull request #592
Opened 2024-10-15 10:41 UTC by shamun-khatri

## Linked Issue(s)

Closes #559 

## Proposed changes (including videos or screenshots)

I have used process.exit() in one place (useEffect hook where it checks if  AppState === TERMINATED) instead of exit() that is not working. I have tried to solve this issue by debugging and trying other methods but noting works but this.

Here is a screenshot of working terminal detach.

![image](https://github.com/user-attachments/assets/8665439f-dfec-485a-b01f-2730ce72a8b5)

## Further comments

I hope this will get merged. But if you think I could do better then tell me I will change things along.

2024-10-15 10:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/middlewarehq/middleware?pullRequest=592) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/middlewarehq/middleware?pullRequest=592) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/middlewarehq/middleware?pullRequest=592) it.</sub>

2024-10-15 10:49 UTC, jayantbh requested changes
I have a feeling that this doesn't always work.
For example, if you let the ./dev.sh script run till completion (or long enough), and then press X, it doesn't quit successfully.

I noticed you replaced `ink`'s `exit` call with `process.exit`, which is fine, but the dependencies remain unchanged.

I think I'd have kept both the `process.exit` and `exit` calls in there.

Additionally...
There's a lot of whitespace changes which I'm not sure are intentional.

<img width="695" alt="image" src="https://github.com/user-attachments/assets/1f597d49-d8ec-454a-9457-e4ca6a6a37b1">

2024-10-15 11:19 UTC, shamun-khatri commented
Yes, whitespaces are not intentional I have tried many other things that's why they are there.

But I got confused about what will not work.  You said in a long-running process that might now work why?  

Also, what does it mean that dependencies remain unchanged?

2024-10-15 11:28 UTC, shamun-khatri commented
One thing I forgot about I have tried keeping both `exit()` and `process.exit()` and keeping both also works.

And I have also tried keeping the app(process) running for 5 minutes and then tried X with only `process.exit()` and it still works fine.

2024-10-15 12:57 UTC, jayantbh commented
> But I got confused about what will not work.
Honestly, same. 😆 

I wasn't able to reliably reproduce that issue in the past.

But yeah, I think call `exit` and then `process.exit`. Call both. `exit` from `ink` allows it to do any needed cleanup before actual exit.

And do remove any unintended code/whitespace changes. I think that'll be it for this PR.

2024-10-16 07:45 UTC, thesujai commented
I hovered around inks codebase and found the reason exit() isn't working is some processes are still active. So the exit() by useApp isn't detaching the terminal. 
The processref.current.kill() call in the handleExit is not working as intended. 

So this solution introduced here might be a hacky way to do things, but it doesn't break anything. Just we can do a check that after calling exit(), if the process is still not killed, then call the process.exit(0) (to keep in mind this isn't forced as code 0 is to safely kill the process). This will ensure that no process is running after the process is unmounted. Else failure to do so might result in terminal being unmounted, but some services still running in the bg.

2024-10-16 07:56 UTC, jayantbh commented
Interesting. Yeah I can see how that happens.
How do we check if a process hasn't safely and completely exited?

2024-10-16 08:50 UTC, thesujai commented
After exit() call in useEffect(), can do:
 ```
if(processRef.current) {
process.exit(0);
}
```

2024-10-16 11:48 UTC, thesujai commented
> But why some process is still running there after running Ikn's exit()

Try running git blame on this file and see what introduced this bug(Maybe it worked before, not sure)

> are you raising a PR for this

No, and feel free to update this branch. Good job!

2024-10-17 07:32 UTC, jayantbh requested changes

2024-10-17 07:32 UTC, jayantbh commented on cli/source/app.tsx
> +      }
Why the `processRef` check here?
Also, this doesn't look formatted right.

2024-10-17 14:43 UTC, jayantbh commented
I understand the intent, but given that you didn't really do anything with processRef itself, and that `exit` is being called anyway, I think it's okay to just `kill` it.

A check for `processRef` would fit better if we were doing something with it directly or indirectly.

Right now if `processRef` happens to not be set, then the UI is potentially just not going to exit properly, which isn't desired behaviour either.

2024-10-17 15:49 UTC, shamun-khatri commented
Ok, I will just kill that and remove unnecessary checks.I have joined the community on slack thanks for sharing.

2024-10-17 17:06 UTC, shamun-khatri commented
I made changes. Please have a look.

2024-10-18 11:45 UTC, jayantbh commented
<img width="478" alt="image" src="https://github.com/user-attachments/assets/00953638-32f9-4a8d-888d-b6341e1ae433">
@shamun-khatri, please use better commit names to better reflect the changes within.

I wrote about this a while ago.
https://dev.to/middleware/not-heres-how-to-write-actually-good-commit-messages-hint-its-not-just-adding-commit-lint-j2i

2024-10-19 04:44 UTC, shamun-khatri commented
@jayantbh I have renamed the commit. I tried my best to write that but if you thing I am still missing anything then do let me know.

2024-10-22 16:49 UTC, jayantbh commented
@shamun-khatri does it count now? I assigned the PR to you, which I think you can do yourself too.

2024-10-22 16:50 UTC, jayantbh approved these changes

2024-10-22 16:53 UTC, merged

2024-10-22 16:56 UTC, shamun-khatri commented
@jayantbh Thanks, finally it is merged. will look forward to contributing more to middleware.