fix: updated Next to 14.2.16
middlewarehq/middleware pull request #614
Opened 2024-10-26 08:38 UTC by Reterics

## Linked Issue(s)

Fixes #597

## Acceptance Criteria fulfillment

Viewed/Tested pages:

 - [x] /teams
    - [x] Add, remove, edit teams
 - [x] /dora-metrics
    - [x] Settings -> Configure Production branches popup
    - [x] Pull Request Insights
    - [x] Calendar date changing
 - [x] /integrations 
    - [x] Removed Token, configured again
 - [x] /settings
 - [x] /system-logs
 - [x] Opened Help Assistant

## Proposed changes (including videos or screenshots)

According to the article on https://nextjs.org/blog/next-15, Next.js 15 is officially stable and ready for production, so I made 2 commits in this PR: (_Reason: in case if we need Next.js 14 instead_)

 1. I updated to version 14, and did my testcases above
 2. and then updated to 15 and did them again.

![image](https://github.com/user-attachments/assets/8f843e32-869b-4830-b0b6-9b788e94a108)

## Further comments

UI related warnings were there before the update as well such as:  (There were not introduced in this PR)
 - _"CreateTeams.tsx:259 Warning: A props object containing a "key" prop is being spread into JSX:"_
 - _"DeploymentInsightsOverlay.tsx:364 Warning: Each child in a list should have a unique "key" prop."_

2024-10-28 05:27 UTC, jayantbh commented
Well, that's a bigger PR than I was expecting. 😄 
Let's get this merged before hacktoberfest ends! 👌🏽 🚀

2024-10-28 05:30 UTC, jayantbh requested changes
Honestly the change I'm requesting at the moment isn't even worth blocking the PR over, except that the contributing guide changed significantly and this might need to weird confusions if this were to be merged as is.

Also surprised that there's not bigger breakages or type changes. We'll check this PR locally once.

2024-10-28 05:30 UTC, jayantbh commented on .github/workflows/pre-commit.yml
If you look at the latest version of contributing.md, you'll see that this stuff isn't there anymore, replaced by something else. Might need to rebase.

2024-10-28 06:37 UTC, jayantbh commented
Type checking doesn't seem to work via the CLI, **but I suspect it isn't actually related to this PR**.

```
➜  web-server git:(feat/next-upgrade) yarn tsc                                                      
yarn run v1.22.22
$ /Users/jayant/Projects/dora-metrics/web-server/node_modules/.bin/tsc
/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:116479
      throw e;
      ^

RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at recursiveTypeRelatedTo (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:60782:18)
    at isRelatedTo (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:60199:122)
    at checkTypeRelatedTo (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:59834:20)
    at isTypeRelatedTo (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:59778:14)
    at isTypeAssignableTo (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:58892:12)
    at typeMaybeAssignableTo (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:64446:11)
    at /Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:64463:58
    at filter (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:169:23)
    at filterType (/Users/jayant/Projects/dora-metrics/web-server/node_modules/typescript/lib/tsc.js:64752:24)

Node.js v22.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2024-10-28 10:44 UTC, jayantbh commented
Okay, the issue I mentioned above is now fixed in main. Please rebase, address the super trivial comment left, and I think we're good.

2024-10-28 16:26 UTC, Reterics commented on .github/workflows/pre-commit.yml
Removed contributing.md from this PR, and i rebased on origin/main

2024-10-28 16:28 UTC, Reterics commented
> Okay, the issue I mentioned above is now fixed in main. Please rebase, address the super trivial comment left, and I think we're good.

After rebase i verified with "yarn tsc " you mentioned above. It is working. Hopefully it will be fine now.

2024-10-28 16:29 UTC, jayantbh commented
Just confirming, did `yarn tsc` in the web-server module work fine for you?

2024-10-28 17:19 UTC, Reterics commented
> Just confirming, did `yarn tsc` in the web-server module work fine for you?

Yes it is working fine. (both Ubuntu and Windows 11)
![image](https://github.com/user-attachments/assets/da4fb1f0-6fac-41e1-a6d9-15127582ef8c)

![image](https://github.com/user-attachments/assets/037957d5-fc89-438a-8885-f890f75d6372)

2024-10-30 19:43 UTC, jayantbh approved these changes

2024-10-30 19:43 UTC, jayantbh commented
Great stuff, @Reterics!
Thank you!

2024-10-30 19:44 UTC, merged